import { NextResponse } from "next/server"

export async function GET() {
  const categories = [
    { id: "all", name: "Все услуги" },
    { id: "tattoo", name: "Татуировка" },
    { id: "piercing", name: "Пирсинг" },
    { id: "permanent", name: "Перманент" },
    { id: "removal", name: "Удаление" },
    { id: "consultation", name: "Консультация" },
  ]

  const services = [
    {
      id: "1",
      title: "Разработка эскиза",
      description: "Индивидуальный подход к каждому клиенту. Создание уникального дизайна по вашим пожеланиям.",
      priceFrom: 3000,
      priceTo: null,
      duration: "1-3 дня",
      category: "tattoo",
      master: {
        id: "1",
        name: "Алексей Смирнов",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
        rating: 4.9,
      },
      popular: true,
    },
    {
      id: "2",
      title: "Тату (маленькое)",
      description: "Татуировка размером до 5 см. Включает консультацию и эскиз.",
      priceFrom: 5000,
      priceTo: 10000,
      duration: "1-2 часа",
      category: "tattoo",
      master: {
        id: "2",
        name: "Мария Волкова",
        avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
        rating: 5.0,
      },
      popular: true,
    },
    {
      id: "3",
      title: "Тату (среднее)",
      description: "Татуировка размером 5-15 см. Несколько сеансов по необходимости.",
      priceFrom: 10000,
      priceTo: 25000,
      duration: "2-4 часа",
      category: "tattoo",
      master: {
        id: "1",
        name: "Алексей Смирнов",
        avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
        rating: 4.9,
      },
      popular: false,
    },
    {
      id: "4",
      title: "Тату (большое/рукав)",
      description: "Крупная работа от 15 см. Возможна рассрочка. Предварительная консультация обязательна.",
      priceFrom: 25000,
      priceTo: null,
      duration: "от 4 часов",
      category: "tattoo",
      master: {
        id: "3",
        name: "Дмитрий Козлов",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
        rating: 4.8,
      },
      popular: true,
    },
    {
      id: "5",
      title: "Пирсинг уха",
      description: "Профессиональный пирсинг мочки или хряща. Стерильные материалы.",
      priceFrom: 1500,
      priceTo: 3000,
      duration: "30 мин",
      category: "piercing",
      master: {
        id: "3",
        name: "Дмитрий Козлов",
        avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
        rating: 4.8,
      },
      popular: true,
    },
    {
      id: "6",
      title: "Перманентный макияж бровей",
      description: "Натуральный вид бровей. Техника пудровое напыление или микроблейдинг.",
      priceFrom: 8000,
      priceTo: 15000,
      duration: "2-3 часа",
      category: "permanent",
      master: {
        id: "6",
        name: "Елена Соколова",
        avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop&crop=face",
        rating: 4.6,
      },
      popular: true,
    },
    {
      id: "7",
      title: "Удаление тату лазером",
      description: "Современное оборудование. Минимальный дискомфорт. Требуется несколько сеансов.",
      priceFrom: 2000,
      priceTo: 8000,
      duration: "30-60 мин",
      category: "removal",
      master: {
        id: "5",
        name: "Игорь Новиков",
        avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
        rating: 4.9,
      },
      popular: false,
    },
    {
      id: "8",
      title: "Консультация",
      description: "Обсуждение идеи, выбор места, размера и стиля. Бесплатно при заказе тату.",
      priceFrom: 0,
      priceTo: 500,
      duration: "30-60 мин",
      category: "consultation",
      master: {
        id: "4",
        name: "Анна Петрова",
        avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
        rating: 4.7,
      },
      popular: false,
    },
  ]

  return NextResponse.json({ services, categories })
}
