import { NextResponse } from "next/server"

export async function GET() {
  const masters = [
    {
      id: "1",
      name: "Алексей Смирнов",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=300&fit=crop&crop=face",
      specialty: "Тату-мастер, Художник",
      rating: 4.9,
      reviewsCount: 120,
      location: "Москва, м. Бауманская",
      styles: ["Реализм", "Графика", "Блэкворк"],
      verified: true,
      experience: "10 лет",
      worksCount: 500,
    },
    {
      id: "2",
      name: "Мария Волкова",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&h=300&fit=crop&crop=face",
      specialty: "Тату-мастер",
      rating: 5.0,
      reviewsCount: 89,
      location: "Москва, м. Арбатская",
      styles: ["Акварель", "Минимализм", "Цветная тату"],
      verified: true,
      experience: "7 лет",
      worksCount: 350,
    },
    {
      id: "3",
      name: "Дмитрий Козлов",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&h=300&fit=crop&crop=face",
      specialty: "Тату-мастер, Пирсинг",
      rating: 4.8,
      reviewsCount: 156,
      location: "Москва, м. Тверская",
      styles: ["Традишнл", "Олд Скул", "Нью Скул"],
      verified: true,
      experience: "12 лет",
      worksCount: 800,
    },
    {
      id: "4",
      name: "Анна Петрова",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=300&fit=crop&crop=face",
      specialty: "Тату-мастер, Художник",
      rating: 4.7,
      reviewsCount: 67,
      location: "Москва, м. Китай-город",
      styles: ["Дотворк", "Геометрия", "Орнаментал"],
      verified: false,
      experience: "5 лет",
      worksCount: 200,
    },
    {
      id: "5",
      name: "Игорь Новиков",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=300&fit=crop&crop=face",
      specialty: "Тату-мастер",
      rating: 4.9,
      reviewsCount: 203,
      location: "Москва, м. Курская",
      styles: ["Реализм", "Портреты", "Чикано"],
      verified: true,
      experience: "15 лет",
      worksCount: 1200,
    },
    {
      id: "6",
      name: "Елена Соколова",
      avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=300&fit=crop&crop=face",
      specialty: "Тату-мастер, Перманент",
      rating: 4.6,
      reviewsCount: 45,
      location: "Москва, м. Парк Культуры",
      styles: ["Минимализм", "Леттеринг", "Микро"],
      verified: true,
      experience: "4 года",
      worksCount: 150,
    },
  ]

  return NextResponse.json({ masters })
}
